config/routes.rb
Rails.application.routes.draw do
 root "pages#home"
 get  "about", to:"pages#about"
 resources :articles 
 get 'signup', to: 'users#new'
 resources :users, except: [:new]
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 get 'logout', to: 'sessions#destroy'
 resources :categories, except: [:destroy]
end

app/models/article.rb
class Article <ApplicationRecord 
   belongs_to :user
   has_many :article_categories
   has_many :categories, through: :article_categories
   validates :title,presence:true,length:{minimum:6,maximum:100}
   validates :description,presence:true,length:{minimum:10,maximum:300}
   
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  
  def show 
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end
  
  def edit 
    
  end

  def create
   @article =Article.new(article_params)
   @article.user = current_user
   if @article.save
    flash[:notice] = "Article was created successfully."

    redirect_to @article
   else 
    render :new, status: :unprocessable_entity, content_type: "text/html"
          headers["Content-Type"] = "text/html"
   end  
end


  def update
    
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to  @article
    else
      render 'edit'
    end
  end


  def destroy
    
    @article.destroy
    redirect_to articles_path, status: :see_other
  end


  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end 

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
          <% if article.user %>
          by <%= link_to article.user.username, user_path(article.user) %>
        <% end %>
        <% if article.categories.any? %>
        <div class="mt-2"><%= render article.categories %></div> 
      <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div> 

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
  <div class="col-10">
  <%= render 'shared/errors' , obj: @article%>
    <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
      </div>
      <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-label text-light" %>
        <div class="col-10"> 
          <%= f.collection_select(:category_ids, Category.all, :id, :name,
          { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
        </div>
      </div>

        <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
      </div>
    <% end %>
  </div>
  <div class="mb-3">
  <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
</div>
</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create a new article</h1>
  <%= render 'form' %>
</div> 

app/views/articles/show.html.erb
  <div id="page-content">
  <h2 class="text-center mt-4"><%= @article.title %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
          <div class="mt-2"><%= render @article.categories %></div> 
        <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && @article.user == current_user %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", data: {turbo_method: :delete,turbo_confirm: "Are you sure?"}%>
            <% end %>
            </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div> 